# Generated by Django 5.0.1 on 2024-01-12 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='cat',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='pdetails',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='pimage',
            new_name='portrait',
        ),
    ]
