# Generated by Django 5.0.1 on 2024-01-12 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0002_rename_cat_services_categories_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='pro',
        ),
    ]
