# Generated by Django 5.0.1 on 2024-01-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0003_rename_services_pro'),
    ]

    operations = [
        migrations.CreateModel(
            name='cont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=40)),
                ('customer_email', models.CharField(max_length=40)),
                ('customer_concern', models.CharField(max_length=40)),
                ('customer_message', models.CharField(max_length=100)),
            ],
        ),
    ]
