# Generated by Django 5.0.1 on 2024-01-18 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_id',
        ),
    ]
