# Generated by Django 5.0.1 on 2024-03-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0007_remove_cart_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='summary',
            field=models.CharField(default=1, max_length=1000, verbose_name='Service Summary'),
            preserve_default=False,
        ),
    ]
