# Generated by Django 5.0.1 on 2024-03-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0008_pro_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='Categories',
            field=models.IntegerField(choices=[(1, 'forest'), (2, 'Art'), (3, 'people')], verbose_name='Category'),
        ),
    ]
