# Generated by Django 5.0.1 on 2024-03-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0009_alter_pro_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='writer',
            field=models.CharField(default=1, max_length=200, verbose_name='writer name'),
            preserve_default=False,
        ),
    ]
