# Generated by Django 5.0.1 on 2024-03-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0010_pro_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='subj',
            field=models.CharField(default=1, max_length=200, verbose_name=' writer subj'),
            preserve_default=False,
        ),
    ]
